ams/models.py
 
from datetime import date ,datetime
from ams import db ,login_manager 
from flask_login import UserMixin
from flask_login._compat import unicode

@login_manager.user_loader
def load_user(user_id): 
    return EOStudent.query.get(int(user_id))
 


#Admin User
class EOAdminUser(db.Model,UserMixin):
    __tablename__ = 'eoadminuser'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password = db.Column(db.String(60), nullable=False)
    is_admin = db.Column(db.Boolean, nullable=False, default=True)


#Session class
class EOGrade(db.Model):
    __tablename__ = 'eograde'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), unique=True, nullable=False)
    acadmic_year = db.Column(db.Integer, nullable=False, default='2021')
    info = db.Column(db.Text, nullable=False)
    #eostudent_list = db.relationship("EOStudent", backref="eoclass", lazy=True)

    #Student


class EOStudent(db.Model,UserMixin):
    __tablename__ = 'eostudent'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(20), unique=False, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    gender = db.Column(db.String(120), nullable=False,default='NA')
    dob = db.Column(db.Date(), nullable=True, default='2020-01-01')
    password = db.Column(db.String(60), nullable=False)
    unique_face_byte = db.Column(db.Text, nullable=True)
    image_url = db.Column(db.String(20), nullable=False, default='default.jpg')
    inactive = db.Column(db.Boolean, nullable=False, default=False)
    is_admin = db.Column(db.Boolean, nullable=False, default=False) 
    
    eograde_id = db.Column(db.Integer, db.ForeignKey(
        "eograde.id"), nullable=False)
    #eoattendance_list = db.relationship("EOAttendance", backref="eostudent", lazy=True)
    
    def is_face_uiid_configured(self):
        return  self.unique_face_byte is not None
     


class EOAttendance (db.Model):
    __tablename__ = 'eoattendance'

    id = db.Column(db.Integer, primary_key=True)
    busi_date = db.Column(db.Date(), nullable=False, default=date.today())
    eostudent_id = db.Column(db.Integer, db.ForeignKey(
        "eostudent.id"), nullable=False)
    eograde_id = db.Column(db.Integer, db.ForeignKey(
        "eograde.id"), nullable=False)
    is_present = db.Column(db.Boolean, nullable=False, default=False)
    on_leave = db.Column(db.Boolean, nullable=False, default=False)

ams/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo


class RegistrationForm(FlaskForm):
    username = StringField('Username',
                           validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password',
                                     validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Sign Up')


class LoginForm(FlaskForm):
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember = BooleanField('Remember Me')
    submit = SubmitField('Login')

ams/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from ams.config import Config
from flask_session import Session



db = SQLAlchemy()
appSession = Session()
login_manager = LoginManager()
login_manager.login_view = "auth.index"
login_manager.login_message_category = "info"


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)
    login_manager.init_app(app)
    #appSession.init_app(app)
   

   
    from ams.auth.routes import auth
    from ams.users.routes import users
    # from flaskblog.posts.routes import posts
    # from flaskblog.main.routes import main
    # from flaskblog.sandbox.routes import sandbox
    # from flaskblog.errors.handlers import errors

    app.register_blueprint(users)
    app.register_blueprint(auth)
    # app.register_blueprint(main)
    # app.register_blueprint(sandbox)
    # app.register_blueprint(errors)

    return app

#db.create_all()

#from ams import routes

ams/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint,session
from flask_login import login_user, logout_user, current_user, login_required

# from ams import app
from ams.forms import RegistrationForm, LoginForm
from ams.models import EOAdminUser,EOStudent
from ams.img_capture import capture_video
from ams import db


users = Blueprint("users", __name__)


posts = [
    {
        'author': 'Corey Schafer',
        'title': 'Blog Post 1',
        'content': 'First post content',
        'date_posted': 'April 20, 2018'
    },
    {
        'author': 'Jane Doe',
        'title': 'Blog Post 2',
        'content': 'Second post content',
        'date_posted': 'April 21, 2018'
    }
]

 
@users.route("/home")
@login_required
def home():      
    eoStudent = EOStudent.query.get(session['id'])
    return render_template('home.html', user=eoStudent)


@users.route("/profile")
@login_required
def profile():
    return render_template('profile.html', title='Profile')

@users.route("/face_config")
@login_required
def face_config():
    student = EOStudent.query.get(session['id'])
    file_Path = capture_video(student.name)
    student = EOStudent.query.get(student.id)
    if file_Path:
        student.unique_face_byte =file_Path
        db.session.add(student)
        db.session.commit()
        return redirect(url_for("users.home"))
    return render_template('home.html', user=student)


@users.route("/attandence")
@login_required
def attandence():
    student = EOStudent.query.get(session['id'])
    file_Path = capture_video(student.name)
    student = EOStudent.query.get(student.id)
    if file_Path:
        student.unique_face_byte =file_Path
        db.session.add(student)
        db.session.commit()
        return redirect(url_for("users.home"))
    return render_template('home.html', user=student)


# @users.route("/account", methods=['GET', 'POST'])
# def register():
#     form = RegistrationForm()
#     if form.validate_on_submit():
#         flash(f'Account created for {form.username.data}!', 'success')
#         return redirect(url_for('home'))
#     return render_template('register.html', title='Register', form=form)


# @users.route("/login", methods=['GET', 'POST'])
# def login():
#     form = LoginForm()
#     if form.validate_on_submit():
#         if form.email.data == 'admin@blog.com' and form.password.data == 'password':
#             flash('You have been logged in!', 'success')
#             return redirect(url_for('home'))
#         else:
#             flash('Login Unsuccessful. Please check username and password', 'danger')
#     return render_template('login.html', title='Login', form=form)

ams/templates/home.html
{% extends "layout.html" %}
{% set active_page = "home" %}
{% block content %} 

 

    <div class="container-fluid">
        <h1 class="mt-4">Dashboard</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item"><a>AMS</a></li>
            <li class="breadcrumb-item active">Dashboard</li>
        </ol>
        <div class="card mb-4">
            <div class="card-body">
                <p class="mb-0">
                    Your daily attendanece status . {{user.id}} --{{user.name}}
                    {% if user.is_face_uiid_configured() %}   
                    <code>You have not configure the face recoginzation, Configure it now</code> 
                    {% endif %}
                </p>
            </div>
        </div>
        <div class="content-section" style="height: 62vh;" > 
            <!-- {% if user.is_face_uiid_configured() %}             
            <h3>You have configurered your face recoginzation</h3>
            {% else %}
            <a type="button" class="btn btn-primary" href="{{ url_for('users.face_config') }}">Configure Now</a>
            {% endif %} -->

            <div class="row">
                <div class="col-12 col-lg-6">
                  
                    {% if user.is_face_uiid_configured() %}             
                    <div class="row align-items-center mb-8 aos-init aos-animate" data-aos="fade-up">
                        <div class="col-4 col-lg-5">                      
                        
                          <img src="{{ url_for('static', filename='images/configured.svg') }}" alt="..." class="img-fluid">
          
                        </div>
                        <div class="col-8 col-lg-7">
                          
                          <!-- Heading -->
                          <h3 class="font-weight-bold mb-2">
                            Configured 
                          </h3>
          
                          <!-- Text -->
                          <p class="text-gray-700 mb-0">
                            You have valid face recoginzation configuration.
                          </p>
          
                        </div>
                      </div> 

                      <div class="row align-items-center mb-8 aos-init aos-animate" data-aos="fade-up">
                        <div class="col-4 col-lg-5">
                          
                          <!-- Image -->
                          <img src="{{ url_for('static', filename='images/attendance.png') }}" alt="..." class="img-fluid">
          
                        </div>
                        <div class="col-8 col-lg-7">

                            <div class="card"> 
                                <div class="card-body">
                                  <h3 class="card-title font-weight-bold mb-2">Attendanece</h3>
                                  <p class="card-text">If you haven't marked your today's attendanece , Then do it now.</p>
                               <a type="button" class="btn btn-primary"  href="{{ url_for('users.attandence') }}">Attendanece</a>
                                </div>
                              </div>
                           
                        </div>
                      </div>  


                    {% else %}
                    <div class="row align-items-center mb-8 aos-init aos-animate" data-aos="fade-up">
                        <div class="col-4 col-lg-5">                      
                        
                          <img  src="{{ url_for('static', filename='images/config_pendding.png') }}" alt="..." class="img-fluid">
          
                        </div>
                        <div class="col-8 col-lg-7">
                          
                          <!-- Heading -->
                          <h3 class="font-weight-bold mb-2">
                            Configured Pendding
                          </h3>
          
                          <!-- Text -->
                          <p class="text-gray-700 mb-0">
                             Configure you face recoginzation picture, Click on config now button 
                            <code>Press Key "Q" in keyboard to proceed to save the your Picture</code> 
                          </p>
                          <a type="button" class="btn btn-primary" href="{{ url_for('users.face_config') }}">Configure Now</a>
          
                        </div>
                      </div> 

                      <div class="row align-items-center mb-8 aos-init aos-animate" data-aos="fade-up">
                        <div class="col-4 col-lg-5">
                          
                          <!-- Image -->
                          <img src="{{ url_for('static', filename='images/attendance.png') }}" alt="..." class="img-fluid">
          
                        </div>
                        <div class="col-8 col-lg-7">
                          
                          <!-- Heading -->
                          <h3 class="font-weight-bold mb-2">
                            Attendanece 
                          </h3>
          
                          <!-- Text -->
                          <p class="text-gray-700 mb-0">
                            You haven't configure your face recoginzation picture, first configure that than choose to mark attendance.
                          </p>
          
                        </div>
                      </div>  

                    {% endif %}

               
      
               
              
      
      
                </div>
                 
              </div>
        </div>
        
        <!-- <div class="card mb-4"><div class="card-body text-center">It's secure </div></div> -->
    </div>
     
         
 
         
 
{% endblock content %}

ams/templates/index.html
{% extends "layout.html" %}

{% block content %}
<h1 class="title">
  Logout sucesfully!
</h1>
<h2 class="subtitle">
  Attendanece Managemnt System 
</h2>
{% endblock %}

ams/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
 <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">



    <!-- Bootstrap core CSS -->
  <link href="{{ url_for('static', filename='bootstrap/css/bootstrap.css') }}" rel="stylesheet">
  <!-- Custom styles for this template -->
  <link href="{{ url_for('static', filename='sidebar.css') }}" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}"> 

    {% if title %}
        <title>AMS - {{ title }}</title>
    {% else %}
        <title>Attendanece Managemnt Sytem</title>
    {% endif %}
</head>
<body>



    <div class="d-flex" id="wrapper">
        <!-- Sidebar -->
        {% if current_user.is_authenticated %} 
        <div class="bg-light border-right" id="sidebar-wrapper">
          <div class="sidebar-heading"> <img src="{{ url_for('static', filename='images/ams1.svg') }}" style="height: 50px;"></div>
          <div class="list-group list-group-flush">
            <a class="list-group-item list-group-item-action bg-light {{ 'active' if active_page == 'home' else '' }}" href="{{ url_for('users.home') }}">Dashboard</a>  
            <a class="list-group-item list-group-item-action bg-light {{ 'active' if active_page == 'profile' else '' }}" href="{{ url_for('users.profile') }}">Profile</a>
            <a class="list-group-item list-group-item-action bg-light">Status</a>
          </div>
        </div>
        {% else %}
        <!-- TODO -->
        {% endif %}
       <!-- /#sidebar-wrapper -->
    
        <!-- Page Content -->
        <div id="page-content-wrapper"> 
          <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
            {% if not current_user.is_authenticated %} 
            <img src="{{ url_for('static', filename='images/ams.svg') }}" style="height: 50px;">
            {% endif %}
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
    
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav ml-auto mt-2 mt-lg-0"> 
               
                {% if current_user.is_authenticated %} 
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{current_user.name}}
                  </a>
               

                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">                 
                    <a class="dropdown-item" href="{{ url_for('users.home') }}">Home</a>
                    <a class="dropdown-item" href="{{ url_for('users.profile') }}">Profile</a>                    
                    <div class="dropdown-divider"></div> 
                    <a class="dropdown-item"  href="{{ url_for('auth.logout') }}">Logout</a>                  
                  </div>
                </li>
                {% else %}
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                  </li>
                {% endif %}
              </ul>
            </div>
          </nav>
    
      
           <div class="container-fluid" style="height: 88vh;">
               {% block content %}{% endblock %}  
           </div>
      
        </div>
        <!-- /#page-content-wrapper -->
    
      </div>
      <!-- /#wrapper -->
 

 

  <!-- Bootstrap core JavaScript -->
  <script src="{{ url_for('static', filename='jquery/jquery.js') }}"></script>
  <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.js') }}"></script>

   <!-- Menu Toggle Script -->
   <script>
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
    });
  </script>
</body>
</html>

ams/templates/layout_old.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>AMS - {{ title }}</title>
    {% else %}
        <title>Attendanece Managemnt Sytem</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">AMS</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('auth.index') }}">Home</a>
          
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                {% if current_user.is_authenticated %} 
                     <a class="nav-item nav-link" href="{{ url_for('users.home') }}">Home</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.profile') }}">Account</a>
                    <a class="nav-item nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                {% else %}
                    <a class="nav-item nav-link" href="{{ url_for('auth.login') }}">Login</a>
                    <!-- <a class="nav-item nav-link" href="{{ url_for('auth.register') }}">Register</a> -->
                {% endif %}
              </div>
             
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-12"> 
          {% block content %}{% endblock %}  
        </div>
      
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

ams/templates/login.html
{% extends "layout.html" %}
{% block content %}
<div class="container-fluid">
     
    <div class="content-section">

        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}
            </div>
        {% endif %}
        {% endwith %}


        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted ml-2">
                <a href="#">Forgot Password?</a>
            </small>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('auth.register') }}">Sign Up Now</a>
        </small>
    </div>
    </div>
{% endblock content %}

ams/templates/profile.html
{% extends "layout.html" %}
{% set active_page = "profile" %}
{% block content %}
<div class="container-fluid">
    <h1>Profile Page</h1>
    </div>
{% endblock content %}

ams/templates/register.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{{ url_for('auth.login') }}">Sign In</a>
        </small>
    </div>
{% endblock content %}